# Generated by Django 4.2.4 on 2023-12-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variationChoice', 'variationValue')},
        ),
    ]
