# Generated by Django 4.2.4 on 2023-12-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
