# Generated by Django 4.2.4 on 2023-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productvariation_unique_together'),
        ('Cart', '0002_rename_is_available_cartitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
